import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

/**
 * Sample document generator.
 *
 * Produces a filled compliance document as a PDF so the capture → parse →
 * reconcile loop can be exercised without asking anyone to find a real medical
 * card. Every sample is stamped SAMPLE and carries a synthetic-data notice, so
 * it can never be mistaken for an issued document.
 *
 * The values are drawn from the actual request it is generated for, with a
 * renewed expiry — which is the realistic case: a client sends the *new*
 * certificate, so the date legitimately differs from what is on file, and the
 * review screen has a real difference to show.
 */

export interface SampleDocumentInput {
  documentType: string
  issuedTo: string
  identifier: string
  issuedOn: Date
  expiresOn: Date
  issuingAuthority: string
  /** Extra label/value rows specific to the document type. */
  extra?: Array<[string, string]>
}

const iso = (d: Date) => d.toISOString().slice(0, 10)

export async function generateSampleDocument(input: SampleDocumentInput): Promise<Uint8Array> {
  const pdf = await PDFDocument.create()
  const page = pdf.addPage([612, 792])
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)

  const ink = rgb(0.06, 0.09, 0.16)
  const faint = rgb(0.45, 0.5, 0.58)
  const line = rgb(0.85, 0.88, 0.92)

  let y = 712

  // Watermark — unmissable, and drawn under the content.
  page.drawText('SAMPLE', {
    x: 120,
    y: 330,
    size: 96,
    font: bold,
    color: rgb(0.93, 0.94, 0.96),
    rotate: { type: 'degrees', angle: 30 } as never,
  })

  page.drawText(input.documentType.toUpperCase(), { x: 60, y, size: 16, font: bold, color: ink })
  y -= 18
  page.drawText('Generated sample — synthetic data, not a valid document', {
    x: 60,
    y,
    size: 9,
    font,
    color: faint,
  })
  y -= 24
  page.drawLine({ start: { x: 60, y }, end: { x: 552, y }, thickness: 1, color: line })
  y -= 32

  // The label vocabulary here is exactly what the parser looks for.
  const rows: Array<[string, string]> = [
    ['Issued To', input.issuedTo],
    ['Document Number', input.identifier],
    ['Issue Date', iso(input.issuedOn)],
    ['Expiration Date', iso(input.expiresOn)],
    ['Issuing Authority', input.issuingAuthority],
    ...(input.extra ?? []),
  ]

  for (const [label, value] of rows) {
    page.drawText(`${label}:`, { x: 60, y, size: 10, font, color: faint })
    page.drawText(value, { x: 220, y, size: 11, font: bold, color: ink })
    y -= 26
  }

  y -= 10
  page.drawLine({ start: { x: 60, y }, end: { x: 552, y }, thickness: 1, color: line })
  y -= 22

  for (const note of [
    'This document was generated by Compliance Radar for demonstration purposes.',
    'It contains synthetic data and has no legal effect.',
  ]) {
    page.drawText(note, { x: 60, y, size: 9, font, color: faint })
    y -= 14
  }

  return pdf.save()
}

/** Maps a requested document description onto a plausible sample. */
export function sampleSpecFor(
  documentType: string,
  subject: string,
  identifier: string | null,
  currentExpiry: Date | null,
  baseState: string,
): SampleDocumentInput {
  const now = new Date()
  const renewedFrom = currentExpiry && currentExpiry > now ? currentExpiry : now

  const lower = documentType.toLowerCase()

  if (lower.includes('medical')) {
    // Medical certificates run up to two years.
    const expires = new Date(renewedFrom)
    expires.setUTCFullYear(expires.getUTCFullYear() + 2)
    return {
      documentType: "Medical Examiner's Certificate",
      issuedTo: subject,
      identifier: identifier ?? `ME-${Math.floor(Math.random() * 900000 + 100000)}`,
      issuedOn: now,
      expiresOn: expires,
      issuingAuthority: 'FMCSA National Registry of Certified Medical Examiners',
      extra: [['Examiner Registry Number', '1234567890']],
    }
  }

  if (lower.includes('apportioned') || lower.includes('cab card') || lower.includes('registration')) {
    const expires = new Date(renewedFrom)
    expires.setUTCFullYear(expires.getUTCFullYear() + 1)
    return {
      documentType: 'Apportioned Registration — Cab Card',
      issuedTo: subject,
      identifier: identifier ?? `${baseState}-${Math.floor(Math.random() * 900000 + 100000)}`,
      issuedOn: now,
      expiresOn: expires,
      issuingAuthority: `${baseState} Department of Motor Vehicles`,
      extra: [
        ['Registration Plan', 'International Registration Plan (IRP)'],
        ['Base Jurisdiction', baseState],
      ],
    }
  }

  if (lower.includes('insurance')) {
    const expires = new Date(renewedFrom)
    expires.setUTCFullYear(expires.getUTCFullYear() + 1)
    return {
      documentType: 'Certificate of Liability Insurance',
      issuedTo: subject,
      identifier: identifier ?? `POL-${Math.floor(Math.random() * 9000000 + 1000000)}`,
      issuedOn: now,
      expiresOn: expires,
      issuingAuthority: 'Sample Mutual Insurance Company',
      extra: [['Coverage Limit', '$1,000,000 combined single limit']],
    }
  }

  if (lower.includes('schedule 1') || lower.includes('2290')) {
    const expires = new Date(renewedFrom)
    expires.setUTCFullYear(expires.getUTCFullYear() + 1)
    return {
      documentType: 'Schedule 1 — Heavy Highway Vehicle Use Tax Return (Form 2290)',
      issuedTo: subject,
      identifier: identifier ?? `SCH1-${Math.floor(Math.random() * 900000 + 100000)}`,
      issuedOn: now,
      expiresOn: expires,
      issuingAuthority: 'Internal Revenue Service',
      extra: [['Tax Period', `July ${now.getUTCFullYear()} – June ${now.getUTCFullYear() + 1}`]],
    }
  }

  const expires = new Date(renewedFrom)
  expires.setUTCFullYear(expires.getUTCFullYear() + 1)
  return {
    documentType,
    issuedTo: subject,
    identifier: identifier ?? 'SAMPLE-000000',
    issuedOn: now,
    expiresOn: expires,
    issuingAuthority: `${baseState} issuing agency`,
  }
}
